import 'package:vit_design_system/vit_design_system.dart';
import 'package:flutter/material.dart';

/// A [VitButton] wrapper widget that displays a social login button.
class VitSocialButton extends VitButton {
  /// Creates a [VitSocialButton] with the Google logo.
  const VitSocialButton.google({
    required super.text,
    required super.onPressed,
    super.key,
    super.isDisabled,
    super.isLoading,
    super.darkenFactor,
    super.textStyle,
    super.width,
    super.minWidth,
    super.padding,
    super.expand,
    super.height,
    super.visualDensity,
    super.flex,
    super.borderRadius,
    super.semanticLabel,
    super.hint,
    super.icon,
    super.borderColor,
    super.borderWidth,
    super.disabledColor,
    super.disabledForegroundColor,
    super.iconColor,
    super.backgroundColor = const Color(0xFFF2F3F3),
    super.foregroundColor = const Color(0xFF1F1F1F),
    super.imageAsset = 'assets/google_logo.png',
    super.package = 'vit_design_system',
    super.maxWidth,
  });

  /// Creates a [VitSocialButton] with the Facebook logo.
  const VitSocialButton.facebook({
    required super.text,
    required super.onPressed,
    super.key,
    super.isDisabled,
    super.isLoading,
    super.darkenFactor,
    super.textStyle,
    super.width,
    super.minWidth,
    super.padding,
    super.expand,
    super.height,
    super.visualDensity,
    super.flex,
    super.borderRadius,
    super.semanticLabel,
    super.hint,
    super.icon,
    super.borderColor,
    super.borderWidth,
    super.disabledColor,
    super.disabledForegroundColor,
    super.iconColor,
    super.backgroundColor = const Color(0xFF1B77F0),
    super.foregroundColor = Colors.white,
    super.imageAsset = 'assets/facebook_logo.png',
    super.package = 'vit_design_system',
    super.maxWidth,
  });

  /// Creates a [VitSocialButton] with the Apple logo.
  const VitSocialButton.apple({
    required super.text,
    required super.onPressed,
    super.key,
    super.isDisabled,
    super.isLoading,
    super.darkenFactor,
    super.textStyle,
    super.width,
    super.minWidth,
    super.padding,
    super.expand,
    super.height,
    super.visualDensity,
    super.flex,
    super.borderRadius,
    super.semanticLabel,
    super.hint,
    super.icon,
    super.borderColor,
    super.borderWidth,
    super.disabledColor,
    super.disabledForegroundColor,
    super.iconColor,
    super.backgroundColor = const Color(0xff141415),
    super.foregroundColor = Colors.white,
    super.imageAsset = 'assets/apple_logo.png',
    super.package = 'vit_design_system',
    super.maxWidth,
  });
}
